baseURL: https://www.sunartdiaries.co.uk/
languageCode: en-gb
title: The Sunart Diaries
theme: hugo-coder
enableEmoji: true

permalinks:
  posts: /:year/:month/:title/

params:
  author: David Evans
  info: Life in the Wild West
  description: Ardnamurchan, Morvern, Knoydart
  since: 2018
  avatarurl: images/eagle.jpg

  favicon_32: /favicon-32x32.png
  favicon_16: /favicon-16x16.png
  touchIcon: /apple-touch-icon.png
  
  goatcounter:
    code: sunartdiaries

  enableGitInfo: true

  colorScheme: auto
  hidecolorschemetoggle: false

  social:
    - name: "Instagram"
      icon: fa fa-instagram fa-2x
      weight: 1
      url: https://www.instagram.com/sunartdiaries/
    - name: "RSS"
      icon: fa fa-rss fa-2x
      weight: 2
      url: /index.xml

menu:
  main:
    - name: About
      weight: 1
      url: about/
    - name: Posts
      weight: 2
      url: posts/
    - name: Weather
      weight: 3
      url: https://weather.sunartdiaries.co.uk/
      target: "_blank"
    - name: Birds
      weight: 4
      url: birds/
      target: _new
    - name: Tags
      weight: 5
      url: tags/
    - name: Categories
      weight: 6
      url: categories/
#    - name: Contact
#      weight: 6
#      url: contact/



taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

